language: go

go:
  - 1.13.x

before_script:
  - go get github.com/mattn/goveralls

script:
  - make fmt
  - make lint
  - make test-coverage
  - goveralls -coverprofile=ib-sriov-cni.cover -service=travis-ci
  - make image

before_deploy:
  - docker login -u "$REGISTRY_USER" -p "$REGISTRY_PASS"

deploy:
  # Push image to Dockerhub on merge to master
  - provider: script
    skip_cleanup: true
    script: >
     bash -c '
     docker push $IMAGE_NAME;
     echo done'
    on:
      branch: master
