name: go-build-and-test-amd64
on:
    push:
    pull_request:
    schedule:
      - cron: "0 8 * * 0" # every sunday
jobs:
  build:
    name: build
    strategy:
      matrix:
        go-version: [1.25.x]
        os: [ubuntu-24.04]
        goos: [linux]
        goarch: [amd64]
    runs-on: ${{ matrix.os }}
    steps:
      - name: set up Go
        uses: actions/setup-go@v6
        with:
          go-version: ${{ matrix.go-version }}
      - name: check out code into the Go module directory
        uses: actions/checkout@v6
      - name: build test for ${{ matrix.goarch }}
        env:
          GOARCH: ${{ matrix.goarch }}
          GOOS: ${{ matrix.goos }}
        run: make build
   
  test:
    name: test
    runs-on: ubuntu-24.04
    needs: build
    steps:
      - name: set up Go
        uses: actions/setup-go@v6
        with:
          go-version: 1.25.x
      - name: check out code into the Go module directory
        uses: actions/checkout@v6
      - name: run unit-test image test
        run: make test

  image-test:
    name: image test
    runs-on: ubuntu-24.04
    steps:
      - name: check out the repo
        uses: actions/checkout@v6

      - name: set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: build and test ib-sriov-cni image
        run: make test-image

  coverage:
    runs-on: ubuntu-24.04
    needs: build
    name: coverage
    steps:
      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: 1.25.x
      - name: Check out code into the Go module directory
        uses: actions/checkout@v6
      - name: Go test with coverage
        run: make test-coverage # sudo needed for netns change in test
      - name: Coveralls
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          file: ib-sriov-cni.cover
