name: go-static-analysis
on: [push, pull_request]
jobs:
  golangci:
    name: Lint
    runs-on: ubuntu-24.04
    steps:
      - name: set up Go
        uses: actions/setup-go@v6
        with:
          go-version: 1.25.x
      - name: checkout PR
        uses: actions/checkout@v6
      - name: run make lint
        run: make lint
  shellcheck:
    runs-on: ubuntu-24.04
    steps:
      - name: checkout PR
        uses: actions/checkout@v6
      - name: run make shellcheck
        run: make shellcheck
  hadolint:
    runs-on: ubuntu-24.04
    steps:
      - name: checkout PR
        uses: actions/checkout@v6
      - name: run make hadolint
        run: make hadolint
